Project Development Phase/Sprint 1/Customer Care Registry/registry/views.py
from flask import Blueprint, render_template, request, redirect, session, url_for
import hashlib
import re
from flask_login import login_required, login_user, logout_user
import ibm_db
import uuid
from datetime import date
from .model import Customer

views = Blueprint("blue_print", __name__)
email_regex = r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"
pass_regex = r"^[A-Za-z0-9_-]*$"

customer = Customer()

conn = ibm_db.connect('DATABASE=bludb;HOSTNAME=2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud;PORT=30756;SECURITY=SSL;SSLServerCertificate=DigiCertGlobalRootCA.crt;UID=tdn81266;PWD=7LY8okjAouJf3LoO', '', '')

@views.route('/logout')
@login_required
def logout():
    session.pop('LOGGED_IN_AS')
    logout_user()

    return redirect(url_for('blue_print.login'))

@views.route('/', methods = ['GET', 'POST'])
def login():
    # if method is POST
    if request.method == 'POST':
        # getting the data entered by the user 
        email = request.form.get('email')
        password = request.form.get('password')
        role = request.form.get('role-check')

        msg = ""
        to_show = False

        # validating the inputs entered by the user
        if(not (re.fullmatch(email_regex, email))):
            msg = "Enter a valid email"
            to_show = True

        elif (len(password) < 8):
            msg = "Password must be atleast 8 characters long!"
            to_show = True

        # Admin login
        if email == "admin.ccr@gmail.com":
            if password == "admin.ccr@2022":
                return redirect('/admin/tickets')

            else:
                to_show = True
                password = ""
                msg = "Invalid password!"

        # Customer or Agent
        else:
            if to_show:
                # there is something fishy with the user's inputs
                password = ""

            elif (not to_show):
                # the user's inputs are valid
                # checking if the login credentials are valid
                if role == "Customer":
                    # checking if the entry of the mail entered is present in the database
                    mail_check_query = "SELECT * FROM customer WHERE email = ?"
                    stmt = ibm_db.prepare(conn, mail_check_query)
                    ibm_db.bind_param(stmt, 1, email)
                    ibm_db.execute(stmt)

                    account = ibm_db.fetch_assoc(stmt)

                    if account:
                        # valid customer
                        # i.e, mail is present in the database

                        # checking if the customer entered a valid password now
                        # encrypting the entered password
                        passcode = str(hashlib.sha256(password.encode()).hexdigest())

                        # now checking if the encrypted string is same as that of the one in database
                        if (account['PASSCODE'] == passcode):
                            msg = "Valid Login"
                            to_show = True

                            # creating a customer object
                            customer.set(
                                account['CUST_ID'],
                                account['FIRST_NAME'],
                                account['LAST_NAME'],
                                account['EMAIL'],
                                account['PASSCODE'],
                                account['DATE_JOINED']
                            )

                            session.permanent = False
                            session['LOGGED_IN_AS'] = "CUSTOMER"
                            login_user(customer, remember=True)

                            return redirect('/customer/')

                        else:
                            # customer entered invalid password
                            msg = "Invalid password"
                            password = ""
                            to_show = True

                    else:
                        # invalid customer
                        # i.e, entered mail is not present in the database
                        msg = "User does not exist"
                        email = ""
                        password = ""
                        to_show = True

                else:
                    # user is an Agent
                    print("hello")

        return render_template(
            'login.html',
            to_show = to_show,
            message = msg,
            email = email,
            password = password
        )

    return render_template('login.html')

@views.route('/register', methods = ['GET', 'POST'])
def register():
    # if method is POST
    if request.method == 'POST':
        # getting all the data entered by the user
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        email = request.form.get('email')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        role = request.form.get('role-check')

        msg = ""
        to_show = False

        # validating the inputs 
        if len(first_name) < 2:
            msg = "First Name must be atleast 5 characters long!"
            to_show = True

        elif len(last_name) < 2:
            msg = "Last Name must be atleast 5 characters long!"
            to_show = True

        elif(not (re.fullmatch(email_regex, email))):
            msg = "Please enter valid email"
            to_show = True

        elif((len(password) < 8) or (len(confirm_password) < 8)):
            msg = "Password must be atleast 8 characters long!"
            to_show = True

        elif (password != confirm_password):
            msg = "Passwords do not match"
            to_show = True

        elif (not (re.fullmatch(pass_regex, password))):
            msg = "Enter valid password"
            to_show = True

        if to_show:
            # there is something fishy with the inputs
            password = confirm_password = ""

        # by here the inputs are validated, because to_show is False
        # registering the user / agent with the database
        elif (not to_show):
            if role == "Customer":
                # the user is a Customer
                # checking whether the user with the same email already there
                check_mail_query = "SELECT * FROM customer WHERE email = ?"
                stmt = ibm_db.prepare(conn, check_mail_query)
                ibm_db.bind_param(stmt, 1, email)
                ibm_db.execute(stmt)

                account = ibm_db.fetch_assoc(stmt)

                if account:
                    # user already exists
                    msg = "Email already exists!"
                    to_show = True

                else:
                    # new customer
                    # adding the customer details to the detabase
                    user_insert_query ='''INSERT INTO customer
                            (cust_id, first_name, last_name, email, passcode, date_joined) 
                            VALUES (?, ?, ?, ?, ?, ?)'''

                    # creating a UUID for the customer
                    user_uuid = str(uuid.uuid4())

                    # encrypting the customer's password using SHA-256
                    passcode = str(hashlib.sha256(password.encode()).hexdigest())
                    date_joined = date.today()

                    stmt = ibm_db.prepare(conn, user_insert_query)
                    ibm_db.bind_param(stmt, 1, user_uuid)
                    ibm_db.bind_param(stmt, 2, first_name)
                    ibm_db.bind_param(stmt, 3, last_name)
                    ibm_db.bind_param(stmt, 4, email)
                    ibm_db.bind_param(stmt, 5, passcode)
                    ibm_db.bind_param(stmt, 6, date_joined)

                    ibm_db.execute(stmt)

                    # redirecting the customer to the login page
                    msg = "Account created. Please Login!"
                    to_show = True

                    return render_template('login.html', message = msg, to_show = to_show)
                
            else:
                # the role is Agent
                # can be done in Sprint 2/3
                print("Sprint 2/3")

        return render_template(
            'register.html',
            to_show = to_show,
            message = msg,
            first_name = first_name,
            last_name = last_name,
            email = email,
            password = password,
            confirm_password = confirm_password,
            role = role
        )
    
    return render_template('register.html')

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/admin accagent.html
{% extends 'admin dashboard.html' %}

{% block title %}
    All Requests
{% endblock %}

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/admin agents.html
{% extends 'admin dashboard.html' %}

{% block title %}
    All Agents
{% endblock %}

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/admin dashboard.html
{% extends 'dashboard.html' %}

{% block left %}
    <div class="links-left-div" onload="highlight()">
        <ul id="dash-parent-list">
            <li> 
                <a href="{{ url_for('admin.tickets') }}">
                    <div class="link-items">
                        <div><i class="fa fa-ticket" aria-hidden="true"></i></div>
                        <h3>Tickets</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('admin.agents') }}">
                    <div class="link-items">
                        <div><i class="fa fa-user" aria-hidden="true"></i></div>
                        <h3>Agents</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('admin.accept') }}">
                    <div class="link-items">
                        <div><i class="fa fa-question" aria-hidden="true"></i></div>
                        <h3>Requests</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('admin.about') }}">
                    <div class="link-items">
                        <div><i class="fa fa-info" aria-hidden="true"></i></div>
                        <h3>About</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('admin.support') }}">
                    <div class="link-items">
                        <div><i class="fa fa-comments-o" aria-hidden="true"></i></div>
                        <h3>Feedback</h3>
                    </div>
                </a>
            </li>
        </ul>
    </div>

    <script>
        window.onload = function highlight(){
            id = '{{ id }}'
            var element = document.getElementById('dash-parent-list').children.item(id);
            element.className = "active";
            console.log("function called")
        }
    </script>
{% endblock %}
Footer

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/admin tickets.html
{% extends 'admin dashboard.html' %}

{% block title %}
    All tickets
{% endblock %}

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <!-- Linking css, js, Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <script src="{{ url_for('static', filename='js/pass.js') }}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Linking Watson Assistant -->
    {% block watson %}
    {% endblock %}
</head>
<body>
    {% block alert%}
        {% if to_show %}
            <script>
                alert('{{ message }}')
            </script>
        {% endif %}
    {% endblock %}

    {% block main %}
    {% endblock %}
</body>
</html>

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/cust about.html
{% extends 'cust dashboard.html' %}

{% block title %}
    About
{% endblock %}

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/cust change.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Change Password
{% endblock %}

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/custnew ticket.html
{% extends 'cust dashboard.html' %}

{% block title %}
    New ticket
{% endblock %

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/custprofile.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Welcome {{ customer.first_name }}
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Welcome to CCR!</h1>
        <table class="prof-table">
            <tr>
                <td>First Name</td>
                <td>{{ customer.first_name }}</td>
            </tr>
            <tr>
                <td>Last Name</td>
                <td>{{ customer.last_name }}</td>
            </tr>
            <tr>
                <td>Role</td>
                <td>Customer</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ customer.email }}</td>
            </tr>
            <tr>
                <td>Date joined</td>
                <td>{{ customer.date }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/custsupport.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Support
{% endblock %}

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/custtickets.html
{% extends 'cust dashboard.html' %}

{% block title %}
    All tickets
{% endblock %}

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/dashboard.html
{% extends 'base.html' %}

{% block main %}
    <div class="dashboard-div">
        <nav>
            <div class="dash-nav">
                <div>
                    <div class="dash-img-text">
                        <img src="../static/images/cart logo white-modified.png" class="img-in-nav" alt="logo"/>
                        <h3>Customer Care Registry</h3>
                    </div>
                </div>
                <div>
                    <div class="online-div" onclick="showSettings()">
                        <img src="../static/images/cust.png" class="img-in-nav" alt="logo"/>
                    </div>
                </div>
            </div>
        </nav>
        
        <div class="dash-body">
            <div class="dash-left">
                {% block left %}
                {% endblock %}
            </div>
            <div class="dash-right">
                {% block right %}
                {% endblock %}
            </div>
        </div>

        <div class="settings-menu" id="settings-menu" style="visibility: hidden;">
            <div>
                <p>Want to Logout?</p>
                <a href="{{ url_for('blue_print.login') }}">
                    <button class="logout-btn" type="button">Logout</button>
                </a>
            </div>
        </div>
    </div>

    <script>
        function showSettings(){
            var settings = document.getElementById("settings-menu");

            settings.style.visibility = settings.style.visibility == "hidden" ? "visible" : "hidden";
        }
    </script>
{% endblock %}

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block main %}
    <section class="login-section">
        <div class="login-div">
            <div class="login-header">
                <img src="{{ url_for('static', filename='images/cart logo white.png') }}" class="login-img" alt="logo" />
                <h2>Sign in</h2>
                <p>Use your Registry Account</p>
            </div>
            <div class="login-remind">
                <form action="{{ url_for('blue_print.login') }}" method="POST" class="login-form">
                    <label>Email</label>
                    <input type="email" value="{{ email }}" name="email" placeholder="Enter your email"/>
                    
                    <label>Password</label>
                    <input type="password" value="{{ password }}" name="password" id="password-input" placeholder="Enter your email"/>

                    <div class="show-pass-div">
                        <input type="checkbox" onclick="showPassword()" style="height: 20px;"/>
                        <p>Show Password</p>
                    </div>

                    <div class="role-div">
                        <p>Role : </p>
                        <div>
                            <div>
                                <input type="radio" style="height: 20px;" value="Customer" checked name="role-check"/>
                                <p>Customer</p>
                            </div>
                            <div>
                                <input type="radio" style="height: 20px;" value="Agent" name="role-check"/>
                                <p>Agent</p>
                            </div>
                        </div>
                    </div>

                    <button class="submit-btn" type="submit">Login</button>

                    <div>
                        <a href="#" class="links">Forgot Password?</a> <br> 
                        <div>
                            <a href="{{ url_for('blue_print.register') }}" class="links">Don't have an account yet? Register</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

Project Development Phase/Sprint 1/Customer Care Registry/registry/templates/register.html
{% extends 'base.html' %}

{% block title %}
    Register
{% endblock %}

{% block main %}
    <section class="register-section">
        <div class="register-left">
            <h1>Create your Registry Account</h1>

            <form action="{{ url_for('blue_print.register') }}" method="POST">
                <div class="reg-left-input-div">
                    <div>
                        <label>First Name</label>
                        <input type="text" value="{{ first_name }}" placeholder="First Name" name="first_name" />
                    </div>
                    <div>
                        <label>Last Name</label>
                        <input type="text" value="{{ last_name }}" placeholder="Last Name" name="last_name" />
                    </div>
                </div>
    
                <div class="email-reg">
                    <label>Email</label>
                    <input type="email" value="{{ email }}" placeholder="Your email address" name="email" />
                    <p>This will be your Registry account email</p>
                </div>
    
                <div class="role-div">
                    <p>Role : </p>
                    <div>
                        <div style="margin-top: 0px;">
                            <input type="radio" style="height: 20px;" value="Customer" checked name="role-check"/>
                            <p>Customer</p>
                        </div>
                        <div style="margin-top: 0px;">
                            <input type="radio" style="height: 20px;" value="Agent" name="role-check"/>
                            <p>Agent</p>
                        </div>
                    </div>
                </div>
    
                <div class="reg-left-input-div">
                    <div>
                        <label>Password</label>
                        <input type="password" id="password-input"  value="{{ password }}" placeholder="Password" name="password" />
                    </div>
                    <div>
                        <label>Confirm Password</label>
                        <input type="password" id="password-input"  value="{{ confirm_password }}" placeholder="Confirm password" name="confirm_password" />
                    </div>
                </div>
                <p>Use 8 or more characters with a mix of just letters and numbers</p>
    
                <div class="show-pass-div">
                    <input type="checkbox" onclick="showPassword()" name="show password check"/>
                    <p>Show Password</p>
                </div>
    
                <div class="sign-instead-div">
                    <a href="{{ url_for('blue_print.login') }}" class="cust-link">Sign-in instead</a>
                    <button type="submit" class="submit-btn submit-1">Register</button>
                </div>
            </form>
        </div>
        <div class="register-right">
            <img src="{{ url_for('static', filename='images/cart logo white.png') }}" alt="logo"/>
            <h1>Politeness goes far, yet costs nothing</h1>
        </div>
    </section>
{% endblock %}