Project Development Phase/Sprint 4/Customer Care Registry/registry/routes/agent.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, logout_user
import ibm_db
from .views import conn
from .views import pass_regex
import re
from datetime import datetime
import uuid
import hashlib

USER_AGENT = "AGENT"

agent = Blueprint("agent", __name__)

@agent.route('/agent/profile')
@login_required
def profile():
    '''
        Displaying the agent's details in the dashboard
    '''
    from .views import agent
    
    # extra-level security
    if hasattr(agent, 'first_name'):
        return render_template('agent profile.html', agent = agent, id = 0, user = USER_AGENT)

    else:
        # logging out
        return redirect(url_for('blue_print.logout'))

@agent.route('/agent/assigned')
@login_required
def assigned():
    '''
        Showing the tickets asssigned to the agent by the admin
    '''
    from .views import agent

    if hasattr(agent, 'first_name'):
        # query to fetch the tickets assigned to the agent
        fetch_tickets_query = '''
            SELECT  
                tickets.ticket_id,
                tickets.raised_on,
                customer.first_name, 
                tickets.query_status,
                tickets.issue
            FROM 
                tickets
            JOIN
                customer ON customer.cust_id = tickets.raised_by AND tickets.assigned_to = ?
            ORDER BY
                tickets.raised_on ASC
        '''

        try:
            stmt = ibm_db.prepare(conn, fetch_tickets_query)
            ibm_db.bind_param(stmt, 1, agent.uuid)
            ibm_db.execute(stmt)

            tickets = ibm_db.fetch_assoc(stmt)

            if tickets:
                # some tickets are assigned to the agent
                tickets_list = []

                while tickets != False:
                    temp = []

                    temp.append(tickets['TICKET_ID'])
                    temp.append(str(tickets['RAISED_ON'])[0:10])
                    temp.append(tickets['FIRST_NAME'])
                    temp.append(tickets['QUERY_STATUS'])
                    temp.append(tickets['ISSUE'])

                    tickets_list.append(temp)

                    tickets = ibm_db.fetch_assoc(stmt)           

                return render_template(
                    'agent tickets.html',
                    id = 1,
                    tickets_to_show = True,
                    tickets = tickets_list,
                    msg = "Admin assigned these tickets to you",
                    user = USER_AGENT
                )

            else:
                # admin is yet to assign a ticket for the agent
                return render_template(
                    'agent tickets.html',
                    id = 1,
                    tickets_to_show = False,
                    msg = "Admin is yet to assign a ticket for you",
                    user = USER_AGENT
                )

        except:
            # something wrong went wrong while fetching the tickets
            return render_template(
                'agent tickets.html',
                id = 1,
                tp_show = True,
                message = "Something went wrong! Please Try Again",
                user = USER_AGENT
            )
        
    else:
        # logging out
        return redirect(url_for('blue_print.logout'))

@agent.route('/agent/change', methods = ['GET', 'POST'])
@login_required
def change():
    '''
        Changing the password for the agent
    '''
    from .views import agent
    
    if hasattr(agent, 'first_name'):
        if request.method == 'POST':
            # getting the passwords entered by the agent
            password = request.form.get('password')
            new1 = request.form.get('new-pass-1')
            new2 = request.form.get('new-pass-2')

            msg = ""
            to_show = False

            # validating the passwords entered by the agent
            if((len(password) and len(new1) and len(new2)) < 8):
                password = new1 = new2 = ""
                msg = "Passwords must be atleast 8 characters long!!" 
                to_show = True     

            elif new1 != new2:
                password = new1 = new2 = ""
                msg = "Passwords do not match" 
                to_show = True

            elif password == new1:
                password = new1 = new2 = ""
                msg = "Old and New passwords cannot be same" 
                to_show = True

            elif (not (re.fullmatch(pass_regex, new1))):
                password = new1 = new2 = ""
                msg = "Enter a valid password"
                to_show = True

            # by here the passwords are evaluated
            if not to_show:
                # updating the password of the agent
                # only if, the existing password of the user is valid
                # checking that if is true the database

                # query tp get the existing encrypted password of the agent
                get_password_sha = '''
                    SELECT passcode FROM agent WHERE agent_id = ?
                '''

                try:
                    stmt = ibm_db.prepare(conn, get_password_sha)
                    ibm_db.bind_param(stmt, 1, agent.uuid)
                    ibm_db.execute(stmt)

                    existing = ibm_db.fetch_assoc(stmt)['PASSCODE']

                    # checking 
                        # if the existing encrypted password is equal to
                        # the encrypted one of the one
                    # that is enetered by the agent
                    
                    # passwords match
                    if (existing == str(hashlib.sha256(password.encode()).hexdigest())):
                        # updating the password of the agent

                        # query to update the password
                        update_password_query = '''
                            UPDATE agent SET passcode = ? WHERE agent_id = ?
                        '''

                        # enrcypting the new password entered by the user
                        enc = str(hashlib.sha256(new1.encode()).hexdigest())

                        change = ibm_db.prepare(conn, update_password_query)
                        ibm_db.bind_param(change, 1, enc)
                        ibm_db.bind_param(change, 2, agent.uuid)

                        ibm_db.execute(change)

                        # password is changed
                        # now logging out the agent and re-directing to login page
                        logout_user()
                        
                        return render_template(
                            'login.html',
                            email = agent.email,
                            password = "",
                            to_show = True, 
                            message = "Password changed! Please login"
                        )
                        
                    else:
                        # passwords do not match
                        to_show = True
                        password = new1 = new2
                        msg = "Invalid current password!"

                except:
                    # something happened while changing the password
                    # alerting the agent
                    to_show = True
                    password = new1 = new2
                    msg = "Password not changed! Please try again"

            return render_template(
                'agent change.html',
                id = 2,
                password = password,
                new1 = new1,
                new2 = new2,
                to_show = to_show,
                message = msg,
                user = USER_AGENT
            )

        return render_template('agent change.html', id = 2, user = USER_AGENT)

    else:
        # logging out
        return redirect(url_for('blue_print.logout'))

@agent.route('/agent/about')
@login_required
def about():
    '''
        Showing the about of the application to the agent
    '''
    from .views import agent

    if hasattr(agent, 'first_name'):
        return render_template('agent about.html', id = 3, user = USER_AGENT)

    else:
        # logging out
        return redirect(url_for('blue_print.logout'))

@agent.route('/agent/support', methods = ['GET', 'POST'])
@login_required
def support():
    '''
        Agent can post his/her feedback here
    '''
    from .views import agent

    if hasattr(agent, 'first_name'):
        if request.method == 'POST':
            # collecting the feeback entered by the customer
            feed = str(request.form.get('feed-box')).strip()

            # checking if the feedback entered by the customer is empty! 
            # if so, alerting the customer
            if len(feed) == 0:
                message = "Feedback cannot be empty!"

            else:
                # feedback entered is valid
                # updating the feedback in the database
                insert_feedback_query = '''
                    INSERT INTO feedback 
                        (feed_id, raised_on, raised_by, raised_name, feed)
                    VALUES 
                        (?, ?, ?, ?, ?)
                '''

                try:
                    # creating unique id for the feedback
                    feed_id = str(uuid.uuid4())

                    stmt = ibm_db.prepare(conn, insert_feedback_query)
                    ibm_db.bind_param(stmt, 1, feed_id)
                    ibm_db.bind_param(stmt, 2, datetime.now())
                    ibm_db.bind_param(stmt, 3, "Agent")
                    ibm_db.bind_param(stmt, 4, agent.first_name)

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/admin about.html
{% extends 'admin dashboard.html' %}

{% block title %}
    About
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/admin acc agent.html
{% extends 'admin dashboard.html' %}

{% block title %}
    All Requests
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Pending Requests</h1>
        <div class="new-t-div">
            {% if agents_to_show %}
                <p>{{ msg }}</p>
                
                <table class="agents-table">
                    <tr>
                        <th class="agents-table-heading">AGENT ID</th>
                        <th class="agents-table-heading">EMAIL</th>
                        <th class="agents-table-heading">FIRST NAME</th>
                        <th class="agents-table-heading">JOINED <br/> DATE</th>
                        <th class="agents-table-heading">ACCEPT?</th>
                    </tr>
                    {% for agent in agents %}
                        <tr>
                            <td class="agents-table-element">{{ agent[0][0:5] }}</td>
                            <td class="agents-table-element">{{ agent[1] }}</td>
                            <td class="agents-table-element">{{ agent[2] }}</td>
                            <td class="agents-table-element">{{ agent[3] }}</td>
                            <td class="agents-table-element">
                                <div class="accept-close-div">
                                    <div><i onclick="agree('{{ agent[1] }}')" class="fa fa-check agree" aria-hidden="true"></i></div>
                                    <div><i onclick="deny('{{ agent[1] }}')" class="fa fa-times deny" aria-hidden="true"></i></div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>{{ msg }}</p>
            {% endif %}
        </div>
    </div>

    <script>
        function agree(email){
            var decision = confirm("Do you want to accept the agent?")

            if (decision){
                url = '/admin/' + email + '/True'

                fetch(url, {

                }).then((_res) => {
                    window.location.href = "/admin/accept"
                })
            }
        }

        function deny(email){
            var decision = confirm('If you do not accept the agent, the agent will be deleted from the databse. Is it ok?')
        
            if(decision){
                url = '/admin/' + email + '/False'

                fetch(url, {

                }).then((_res) => {
                    window.location.href = "/admin/accept"
                    console.log("Agent deleted")
                })
            }
        }
    </script>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/admin agent.html
{% extends 'admin dashboard.html' %}

{% block title %}
    All Agents
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>All Agents</h1>

        <div class="new-t-div">
            {% if agents_to_show %}
                <p>{{ msg }}</p>
                <table class="agents-table">
                    <tr>
                        <th class="agents-table-heading">AGENT ID</th>
                        <th class="agents-table-heading">JOINED DATE</th>
                        <th class="agents-table-heading">FIRST NAME</th>
                        <th class="agents-table-heading">LAST NAME</th>
                        <th class="agents-table-heading">EMAIL</th>
                    </tr>
                    {% for agent in agents %}
                        <tr>
                            <td class="agents-table-element">{{ agent[0][0:5] }}</td>
                            <td class="agents-table-element">{{ agent[1] }}</td>
                            <td class="agents-table-element">{{ agent[2] }}</td>
                            <td class="agents-table-element">{{ agent[3] }}</td>
                            <td class="agents-table-element">{{ agent[4] }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>{{ msg }}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/agent about.html
{% extends 'agent dashboard.html' %}

{% block title %}
    About
{% endblock %}

{% block right %}
<div class="profile-div">
    <h1>About</h1>

    <div class="new-t-div">
        <p>You might as well know all these as an agent</p>

        <div class="about-div">
            <ul>
                <li>Customers create ticket to clarify their queries.</li>
                <li>Admin assigns some of the tickets to you.</li>
                <li>Once assigned to you, you chat with the customer.</li>
                <li>During the same, you can answer to the customer.</li>
                <li>Customer closes the ticket once satisfied.</li>
            </ul>

            <a href="{{ url_for('agent.assigned') }}" class="submit-btn new-bol">Tickets assigned</a>
        </div>
    </div>
</div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/agent no.html
{% extends 'base.html' %}

{% block title %}
    Welcome {{ agent.first_name }}!
{% endblock %}

{% block main %}
    <div class="agent-no-show">
        <form method="GET" action="{{ url_for('blue_print.logout') }}">
            <img class="no-show-img" src="../static/images/cart logo white-modified.png" alt="logo"/>
            <h2 class="no-show-header">Welcome agent, {{ agent.first_name }}</h2>
            <p>It seems your account is not yet verified by the admin! So would you please login after a while.</p>
            <button class="logout-btn" type="submit">LOGOUT</button>
        </form>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/agent support.html
{% extends 'agent dashboard.html' %}

{% block title %}
    Feedback
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Feedback</h1>

        <div class="new-t-div">
            <p>Your feedback is highly appreciated!</p>
            <form method="POST" action="{{ url_for('agent.support') }}">
                <textarea name="feed-box" class="ticket-area" maxlength="800" placeholder="Your Feedback..."></textarea>
                <p>* Please make sure the feedback is constructive</p>
                <button type="submit" id="new-ticket" class="submit-btn" style="width: 200px;">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="../static/images/cart logo white-modified.png">
    
    <!-- Linking css, js, Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <script src="{{ url_for('static', filename='js/pass.js') }}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Linking Watson Assistant -->
    {% block watson %}
    {% endblock %}
</head>
<body>
    {% block alert %}
        {% if to_show %}
            <script>
                alert('{{ message }}')
            </script>
        {% endif %}
    {% endblock %}

    {% block main %}
    {% endblock %}
</body>
</html>

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/change password.html
{% extends 'base.html' %}

{% block title %}
    Set New Password
{% endblock %}

{% block main %}
    <div class="bg-main-div">
        <section class="login-section">
            <div class="login-div">
                <div class="login-header">
                    <img src="{{ url_for('static', filename='images/cart logo white.png') }}" class="login-img" alt="logo" />
                    <h2>Change Password</h2>
                    <p>Make sure you don't forget</p>
                </div>
                <div class="login-remind">
                    <form action="/forgot/{{role}}/{{email}}/change" method="POST" class="login-form">
                        <label>Password</label>
                        <input type="password" required name="confirm_password" id="password-input" placeholder="Enter your new password"/>
                        
                        <label>Confirm Password</label>
                        <input type="password" required name="password" id="password-input" placeholder="Confirm password"/>
    
                        <div class="show-pass-div">
                            <input type="checkbox" onclick="showPassword()" style="height: 20px;"/>
                            <p>Show Password</p>
                        </div>
    
                        <button class="submit-btn" type="submit">Change Password</button>
                    </form>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/code.html
{% extends 'base.html' %}

{% block title %}
    Enter the code
{% endblock %}

{% block main %}
    <div class="bg-main-div">
        <section class="login-section extra">
            <div class="login-div">
                <div class="login-header">
                    <img src="{{ url_for('static', filename='images/cart logo white.png') }}" class="login-img" alt="logo" />
                    <h2>Enter the code</h2>
                    <p>Sent to your Registry Account</p>
                </div>
                <div class="login-remind">
                    <form action="/forgot/{{role}}/{{email}}/{{sha}}/" method="POST" class="login-form">
                        <label>Code</label>
                        <input type="text" required name="code-input" placeholder="Enter your code"/>
    
                        <button class="submit-btn" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/customer about.html
{% extends 'cust dashboard.html' %}

{% block title %}
    About
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>About</h1>

        <div class="new-t-div">
            <p>You might as well know all these as a customer</p>

            <div class="about-div">
                <ul>
                    <li>In case you have any doubts, you can create a new ticket.</li>
                    <li>Explain your situation in the ticket legitimately.</li>
                    <li>Admin assigns an agent soon for your ticket.</li>
                    <li>You can chat with the agent to clarify your queries.</li>
                    <li>Close the ticket once you are satisifed.</li>
                </ul>

                <a href="{{ url_for('customer.new') }}" class="submit-btn new-bol">Raise a new ticket</a>
            </div>
        </div>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/customer change.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Change Password
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Change Password</h1>

        <div class="new-t-div">
            <p>Feeling your old password is not good enough?</p>
            
            <div class="change-password-div">
                <form action="{{ url_for('customer.change') }}" method="POST">
                    <label>Password</label>
                    <input name="password" class="change-pass-in" id="password-input" type="password" placeholder="Current Password" />
    
                    <label>New Password</label>
                    <input name="new-pass-1" class="change-pass-in" id="password-input1" type="password" placeholder="New Password" />
    
                    <label>Confirm Password</label>
                    <input name="new-pass-2" class="change-pass-in" id="password-input2" type="password" placeholder="New Password" /> <br/>
                    
                    <p>Use 8 or more characters with a mix of just letters and numbers</p>

                    <div class="show-pass-div">
                        <input type="checkbox" onclick="showPassword()" style="height: 20px;"/>
                        <p>Show Password</p>
                    </div>
                    
                    <button style="width: 150px;" class="submit-btn">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/customer dashboard.html
{% extends 'dashboard.html' %}

{% block left %}
    <div class="links-left-div">
        <ul  id="dash-parent-list">
            <li>
                <a href="{{ url_for('customer.profile') }}">
                    <div class="link-items">
                        <div><i class="fa fa-user" aria-hidden="true"></i></div>
                        <h3>Profile</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.new') }}">
                    <div class="link-items">
                        <div><i class="fa fa-plus" aria-hidden="true"></i></div>
                        <h3>New ticket</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.tickets') }}">
                    <div class="link-items">
                        <div><i class="fa fa-ticket" aria-hidden="true"></i></div>
                        <h3>Tickets</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.change') }}">
                    <div class="link-items">
                        <div><i class="fa fa-key" aria-hidden="true"></i></div>
                        <h3>Change Password</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.about') }}">
                    <div class="link-items">
                        <div><i class="fa fa-info" aria-hidden="true"></i></div>
                        <h3>About</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.support') }}">
                    <div class="link-items">
                        <div><i class="fa fa-comments-o" aria-hidden="true"></i></div>
                        <h3>Feedback</h3>
                    </div>
                </a>
            </li>
        </ul>
    </div>

    <script>
        window.onload = function highlight(){
            id = '{{ id }}'
            var element = document.getElementById('dash-parent-list').children.item(id);
            element.className = "active";
            console.log("function called")
        }
    </script>
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/customer support.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Support
{% endblock %}

Project Development Phase/Sprint 4/Customer Care Registry/registry/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block main %}
    <section class="login-section">
        <div class="login-div">
            <div class="login-header">
                <img src="{{ url_for('static', filename='images/cart logo white.png') }}" class="login-img" alt="logo" />
                <h2>Sign in</h2>
                <p>Use your Registry Account</p>
            </div>
            <div class="login-remind">
                <form action="{{ url_for('blue_print.login') }}" method="POST" class="login-form">
                    <label>Email</label>
                    <input type="email" required value="{{ email }}" name="email" placeholder="Enter your email"/>
                    
                    <label>Password</label>
                    <input type="password" required value="{{ password }}" name="password" id="password-input" placeholder="Enter your email"/>

                    <div class="show-pass-div">
                        <input type="checkbox" onclick="showPassword()" style="height: 20px;"/>
                        <p>Show Password</p>
                    </div>

                    <div class="role-div">
                        <p>Role : </p>
                        <div>
                            <div>
                                <input type="radio" style="height: 20px;" value="Customer" checked name="role-check"/>
                                <p>Customer</p>
                            </div>
                            <div>
                                <input type="radio" style="height: 20px;" value="Agent" name="role-check"/>
                                <p>Agent</p>
                            </div>
                        </div>
                    </div>

                    <button class="submit-btn" type="submit">Login</button>

                    <div>
                        <a href="#" class="links">Forgot Password?</a> <br> 
                        <div>
                            <a href="{{ url_for('blue_print.register') }}" class="links">Don't have an account yet? Register</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}